### PR TITLE
Add gtests, comply to uncrustify, don't build on Windows

### PR DESCRIPTION
**Pull request by jacquelinekay**
http://ci.ros2.org/job/ros2_batch_ci_linux/236
http://ci.ros2.org/job/ros2_batch_ci_osx/155
http://ci.ros2.org/job/ros2_batch_ci_windows/238

### CODE REVIEW

**Comment by tfoote** [comment]
linux build 232 seems to have been deleted?

**Comment by tfoote** [comment]
is this ready for review? it's marked as blocking https://github.com/ros2/demos/pull/7

**Comment by jacquelinekay** [comment]
Yeah, those are old builds. I've updated the links in the description. They are double-referenced from ros2/examples/49

**Comment by jacquelinekay** [comment]
CI update:
OSX green (this package is ignored in OSX)
Windows red, but the state appears consistent with master (connext_dynamic tests fail) (this package is ignored in Windows)

Linux job is pending:
http://ci.ros2.org/job/ros2_batch_ci_linux/236

**Comment by dirk-thomas** [comment]
The Windows build should not break. I don't think this is the case for master currently. How do you get to that conclusion?

**Comment by jacquelinekay** [comment]
I was mistaken, I looked at an earlier `master` branch build that was red, but it was using the `ros2.repos` from my other PR (so it obviously didn't compile):

this is the latest Windows build for this branch:

http://ci.ros2.org/job/ros2_batch_ci_windows/238/

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
Looking at the merged code it seems to have some style problems but the CI jobs don't show that. Now sure why that is the case.

**Comment by jacquelinekay** [comment]
Are you talking about the inconsistent open brace placement?

Yeah, it looks weird. I can try to fix it by hand, I guess.

**Comment by dirk-thomas** [comment]
And the white spaces in CMake. I am wondering why it didn't came up in the CI jobs. Have you confirmed that the tests (including the linters) are actually being run?

**Comment by jacquelinekay** [comment]
The gtests ran and passed on the Linux job for this branch:

http://ci.ros2.org/job/ros2_batch_ci_linux/236/testReport/%28root%29/TestApi/

I'm not sure how to check if the linters ran on Jenkins for specific files.

I have been running `ament_uncrustify` locally on source files and it says
there are no errors for this repo. However, I just learned that
`ament_lint_cmake` exists, ran it locally on the CMakeLists.txt for this
repo, and found style errors.

So, yes, linters are not running for this package on Jenkins. How do I fix
that?

**Comment by dirk-thomas** [comment]
You must call `find_package(ament_lint_auto REQUIRED)` before `ament_package` otherwise it does not get triggered.

**Comment by dirk-thomas** [comment]
This should be checked automatically: https://github.com/ament/ament_lint/pull/26

**Comment by jacquelinekay** [comment]
ros2/rttest/pull/3

**Pull request merged**
